@DotNetInterviewApi_HostAddress = http://localhost:5265

GET {{DotNetInterviewApi_HostAddress}}/weatherforecast/
Accept: application/json

###

### Get all sports
GET {{DotNetInterviewApi_HostAddress}}/api/sport
Accept: application/json

###

### Get sport by ID
GET {{DotNetInterviewApi_HostAddress}}/api/sport/1
Accept: application/json

###

### Get sports by category
GET {{DotNetInterviewApi_HostAddress}}/api/sport/category/Team%20Sports
Accept: application/json

###
